name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          # python -m pip install sphinxcontrib-apidoc
          python -m pip install sphinx-autoapi
          python -m pip install myst-parser
          python -m pip install renku-sphinx-theme
          python -m pip install psycopg
          python -m pip install psycopg2
          python -m pip install jsonschema
          python -m pip install boto3
          python -m pip install rst2pdf
          python -m pip install sphinxtogithub

      - name: make the sphinx docs
        run: |
          #mkdir -p docs/html
          #mkdir -p source
          cp acuity_de_batchingmonitor/readme.md source/readme.md
          cp acuity_de_batchingmonitor/Batching_Monitor_flow.jpg source/Batching_Monitor_flow.jpg
          sphinx-apidoc --force -o source acuity_de_batchingmonitor
          sphinx-build -b html source docs/html
          sphinx-build -b pdf source docs/pdf
          
      - name: Commit changes
        run: |
          git config --global user.email "vignesh.raj@gainwelltechnologies.com"
          git config --global user.name "vignesh-raj-s"
          git add * 
          git commit -m "Sphinx Document Generation"
          git push

