name: Docs
on: [push]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Sphinx build
        run: |
          # mkdir document
          # cp -r code/build/* document/
          mkdir empty-directory
          cd empty-directory
          touch .gitkeep
          git add .
          git commit -m "Commit empty folder in Git with gitkeep"
          git push origin
